#ifndef _Included_com_example_user_jnistudy_JniUtil
#define _Included_com_example_user_jnistudy_JniUtil

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_example_user_jnistudy_JniUtil */
#include <jni.h>
#include <android/log.h>

#define TAG "android_jni"

#define LOG_V(...) __android_log_print(ANDROID_LOG_VERBOSE,TAG ,__VA_ARGS__)
#define LOG_D(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__) // 定义LOGI类型
#define LOG_I(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__) // 定义LOGI类型
#define LOG_W(...) __android_log_print(ANDROID_LOG_WARN,TAG ,__VA_ARGS__) // 定义LOGI类型
#define LOG_E(...) __android_log_print(ANDROID_LOG_ERROR,TAG ,__VA_ARGS__) // 定义LOGI类型

#ifdef __cplusplus
#include <string>
extern "C" {
#endif
/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_user_jnistudy_JniUtil_stringFromJNI
        (JNIEnv *, jclass);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_user_jnistudy_JniUtil_stringFromC
        (JNIEnv *, jclass);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    myJNIEnv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_user_jnistudy_JniUtil_myJNIEnv
        (JNIEnv *, jclass);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    accessFiled
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_user_jnistudy_JniUtil_accessFiled
        (JNIEnv *, jobject);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    accessStaticFiled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_user_jnistudy_JniUtil_accessStaticFiled
        (JNIEnv *, jclass);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    accessMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_user_jnistudy_JniUtil_accessMethod
        (JNIEnv *, jobject);

/*
 * Class:     com_example_user_jnistudy_JniUtil
 * Method:    accessStaticMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_user_jnistudy_JniUtil_accessStaticMethod
        (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_example_user_jnistudy_JniUtil_accessConstructor
        (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_example_user_jnistudy_JniUtil_giveArray
        (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif